- hosts: all
  become: yes
  tasks:
  - name: prerequisites
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      state: latest
      update_cache: true
  - name: docker gpg key
    apt_key:
      url: "https://download.docker.com/linux/debian/gpg"
      state: present
  - name: docker apt repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch sta$h stable"
      state: present
  - name: docker install
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
      update_cache: yes
  - name: docker service
    service:
      name: docker
      state: started

- hosts: jenkins
  become: yes
  tasks:
  - name: "python-pip"
    apt:
      name: "python-pip"
      state: latest
      update_cache: yes
  - name: "docker sdk"
    pip:
      name: docker
  - name